num1 = input("enter first num :")
num2 = input("enter second num :")
add = int(num1) + int(num2)
sub = int(num1) - int(num2)
mul = int(num1) * int(num2)
div = int(num1) / int(num2)
print(add)
print(sub)
print(mul)
print(div)